name: riding_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+21

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  dots_indicator: ^4.0.1
  country_calling_code_picker: ^2.0.1
  pinput: ^5.0.1
  google_maps_flutter: ^2.10.1
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.3
  flutter_html: ^3.0.0-beta.2
  slider_button: ^2.1.0
  flutter_rating_bar: ^4.0.1
  change_app_package_name: ^1.5.0
  local_auth: ^2.3.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  provider: ^6.1.2
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  loading_overlay: ^0.4.2
  another_flushbar: ^1.12.30
  firebase_core: ^3.12.1
  shared_preferences: ^2.5.2
  jiffy: ^6.3.2
  syncfusion_flutter_pdfviewer: ^28.2.9
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4
  launch_review: ^3.0.1
  url_launcher: ^6.3.1
  awesome_notifications: ^0.10.0
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  geolocator: ^10.1.1
  google_maps_place_picker_mb: ^3.1.2

  photo_view: ^0.15.0
  lottie: ^3.3.1
  easy_localization: ^3.0.7+1



dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0
  flutter_polyline_points: ^2.1.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lgu_logo.png"
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/onboarding/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

